var context = require('rabbit.js').createContext('amqp://localhost');
var push = context.socket('PUSH');

push.connect('TEST1', function() {
	push.write("http://www.shure.com/americas/where-to-buy/in-store");
push.write("http://www.head-fi.org/t/696311/shure-se215-ranting-read-this-before-buying-wrong-headphones-or-iem");
push.write("http://www.engadget.com/products/shure/se215/");
push.write("http://headphones.reviewed.com/content/monster-isport-victory-review");
push.write("http://www.trustedreviews.com/monster-isport-immersion-review");
push.write("http://www.whathifi.com/shure/se215/review");
push.write("http://www.expertreviews.co.uk/tvs-entertainment/headphones/51437/shure-se215-review");
push.write("http://www.pcmag.com/article2/0,2817,2399605,00.asp");
push.write("http://www.kijiji.ca/b-headphones/ontario/monster-isport/k0c770l9004");
push.write("http://www.techradar.com/reviews/audio-visual/hi-fi-and-audio/headphones/shure-se215-1288755/review");
push.write("http://www.cnet.com/products/shure-se215-black/user-reviews/");
push.write("http://www.macworld.co.uk/review/headphones/shure-se215-review-3309828/");
push.write("http://www.ebay.com/gds/Shure-SE215-Vs-The-House-of-Marley-EM-JE020-SU-/10000000177710607/g.html");
push.write("http://www.trustedreviews.com/shure-se215-review");
push.write("http://theheadphonelist.com/earphone-buyers-guide/");
push.write("http://lifehacker.com/5800772/how-to-choose-the-perfect-pair-of-headphones");
push.write("http://www.boxwind.com/popular/he/%D7%97%D7%A0%D7%95%D7%AA-%D7%90%D7%95%D7%A4%D7%A0%D7%94");
push.write("http://www.htc.com/us/htc-one-m9-give-away/");
push.write("http://recode.net/2014/10/21/review-apples-ipad-air-2-is-better-but-is-it-better-enough/");
push.write("http://www.macworld.com/article/1164210/buying-guide-find-the-best-ipad-keyboard.html");
push.write("http://www.complex.com/sneakers/2012/08/gear-guide-the-10-best-headphones-for-runners-to-buy-now");
push.write("http://www.outdoorgearlab.com/Sport-Headphones-Reviews/Monster-ISport-Intensity");
push.write("http://the-gadgeteer.com/2011/12/09/monster-isport-immersion-in-ear-headphones-with-controltalk-review/");
push.write("http://www.forbes.com/sites/jaymcgregor/2015/03/17/htc-one-m9-review-release-date-price/");
push.write("http://www.3g.co.uk/PR/August2014/htc-one-m9-release-date-specification-and-price.html");
push.write("http://www.techradar.com/news/phone-and-communications/mobile-phones/htc-one-m9-release-date-where-can-i-get-it--1286561");
push.write("http://thisisflash.com/tag/asus-x455l-review/");
push.write("http://www.tesco.com/direct/asus-x451ca-14-laptop-intel-core-i3-4gb-ram-500gb-white/324-2928.prd");
push.write("http://www.bestbuy.com/site/brands/asus/pcmcat190000050006.c?id=pcmcat190000050006");
push.write("http://www.notebookcheck.net/Asus-X555LN-XO112H-Notebook-Review.125345.0.html");
push.write("http://www.wotorev.com/2014/12/asus-x455l-notebook.html");
push.write("http://www.yugatech.com/search/asus+x455L/");
push.write("http://www.yugatech.com/search/+ASUS+X455L+DRIVER/");
push.write("http://www.yugatech.com/search/+ASUS+X455L+DRIVER/");
push.write("http://www.olx.ph/index.php/classifieds+directory/q/asus+i5");
push.write("http://asus.laptop.product.info/?page=2&orderby=published&src=youtube");
push.write("http://timesofindia.indiatimes.com/tech/reviews/Asus-Fonepad-7-Dual-Sim-review-A-value-for-money-tablet/articleshow/34191113.cms");
push.write("http://www.tipidpc.com/viewitem.php?iid=33606428");
push.write("http://www.engadget.com/2014/11/19/irl-gopro-hero4/");
push.write("http://www.goprobuyersguide.com/hero-3-silver-edition-review");
push.write("http://www.logitech.com/en-us/product/type-plus-keyboard-ipad-air2");
push.write("http://www.t3.com/features/the-best-ipad-air-2-cases-and-covers-to-buy");
push.write("http://www.businessinsider.com/first-ipad-air-2-reviews-2014-10");
push.write("http://www.theglobeandmail.com/technology/gadgets-and-gear/gadgets/review-ipad-air-2-is-gold-for-pros-less-so-for-average-joes/article21217326/");
push.write("http://www.bit.com.au/News/397424,should-you-buy-an-ipad-air-2-from-telstra.aspx");
push.write("http://www.reddit.com/r/ipad/comments/2x8e6z/ipad_air_versus_ipad_air_2_which_do_i_buy/");
push.write("http://www.gardnercreative.co.uk/blog/the-ipad-air-2-more-stuff-to-buy-that-you-dont-need-right/");
push.write("http://us.battle.net/hearthstone/en/forum/13619661/");
push.write("http://www.ehow.com/ehow-tech/blog/tablet-showdown-the-google-nexus-9-vs-the-apple-ipad-air-2/");
push.write("http://www.bleepingcomputer.com/forums/t/553743/ipad-air-2/");
 });

